version: '3'

services:
  app1:
    image: surpreetsingh/first-docker-app
    ports:
      - "3000:3000"
    networks: 
      Surpreet-network:
        ipv4_address: 172.20.0.4

    container_name: app1
  app2:
    image: surpreetsingh/first-docker-app
    ports:
      - "3040:3000"
    networks:
      Surpreet-network:
        ipv4_address: 172.20.0.5
    container_name: app2

networks:
  Surpreet-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
